version: "3"

services:
    backtest:
        image: ${CI_REGISTRY_IMAGE:-paratica}/service-backtest:${VERSION:-latest}
        environment:
            SERVICE_NAME: backtest
            NODE_ENV: ${AWS_ENV}
            REDIS_HOST: $INFRA_MAIN_IP
            REDIS_PORT: 6380
            WAIT_HOSTS: ${DB_IP}:5433
            WAIT_SLEEP_INTERVAL: 10
            WAIT_HOSTS_TIMEOUT: 120
            DB_HOST: ${DB_IP}
            DB_PORT: 5433
            RABBITMQ_HOST: $INFRA_MAIN_IP
            RABBITMQ_PORT: 5672
            API_ROOT: https://aws${CLUSTER_DOMAIN_POSTFIX}/api
            FRONTEND_URL: https://www${CLUSTER_DOMAIN_POSTFIX2}
            CANDLESTICKS_PROVIDER_URL: http://${MASTER_IP}/candlestick
            ZERO_VALUE_USER_ID: 00000000-0000-0000-0000-000000000000
            SERVICE_TAGS: "\
                backend,api,backtest,\
                traefik.enable=true,\
                traefik.http.middlewares.backtest-strip.stripPrefix.prefixes=/api/backtest,\
                traefik.http.routers.backtest-backend.entrypoints=websecure,\
                traefik.http.routers.backtest-backend.rule=PathPrefix(`/api/backtest`),\
                traefik.http.routers.backtest-backend.middlewares=backtest-strip\\,jwt-auth,\
                traefik.http.routers.backtest-backend.tls=true,\
                traefik.http.middlewares.backtest-internal-strip.stripPrefix.prefixes=/api/internal/backtest,\
                traefik.http.routers.backtest-internal.entrypoints=web,\
                traefik.http.routers.backtest-internal.rule=PathPrefix(`/api/internal/backtest`)&&Host(`${MASTER_IP}`),\
                traefik.http.routers.backtest-internal.middlewares=backtest-internal-strip"
