version: 1
task_definition:
  task_execution_role: "arn:aws:iam::945946495384:role/ecsTaskExecutionRole"

  services:
    payment:
      essential: true
      mem_reservation: 64M
      secrets:
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/redis-pass"
          name: REDIS_PASS
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/timescale-user"
          name: DB_USER
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/timescale-pass"
          name: DB_PASS
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/iyzico/api-key"
          name: IYZICO_API_KEY
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/iyzico/secret-key"
          name: IYZICO_SECRET_KEY
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/coinspaid/api-key"
          name: COINSPAID_API_KEY
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/coinspaid/secret-key"
          name: COINSPAID_SECRET_KEY
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/keycloak/admin-client-secret"
          name: KEYCLOAK_ADMIN_CLIENT_SECRET
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/ip-stack/api-key"
          name: IP_STACK_API_KEY
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/kyc/validation-token"
          name: KYC_VALIDATION_TOKEN
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/mq/user"
          name: RABBITMQ_USER
        - value_from: "arn:aws:ssm:eu-central-1:945946495384:parameter/${AWS_ENV}/mq/pass"
          name: RABBITMQ_PASS

        
  placement_constraints:
    - type: memberOf
      expression: attribute:purpose == backend

run_params:
  task_placement:
    strategy:
      - field: instanceId
        type: spread
    constraint:
      - type: memberOf
        expression: attribute:purpose == backend
