version: "3"

services:
    user:
        ports:
            - 0:3000
        logging:
            driver: "awslogs"
            options:
                awslogs-region: eu-central-1
                awslogs-group: user-${AWS_ENV}
                awslogs-stream-prefix: paratica
