version: "3"

services:
    refresh-mv-cronjob:
        ports:
            - 0:3000
        logging:
            driver: "awslogs"
            options:
                awslogs-region: eu-central-1
                awslogs-group: refresh-mv-cronjob-${AWS_ENV}
                awslogs-stream-prefix: paratica
