const REGEXP_PASSWORD = "^(?=.*[A-Za-z])(?=.*?[0-9])(?=.*?[.#?!@$%^&*-]).{8,}";
const REGEXP_EMAIL = /^[A-Z0-9a-z._%+-]{1,}@[A-Za-z0-9.-]{1,}.[A-Za-z]{2,64}$/;
const REGEXP_PHONE_NUMBER = "^[+]";

const MAXIMUM_EMAIL_LENGTH = 50;
const MAXIMUM_PHONE_NUMBER_LENGTH = 20;
const MAXIMUM_PASSWORD_LENGTH = 30;
const MINIMUM_PASSWORD_LENGTH = 8;

module.exports = {
	REGEXP_EMAIL,
	REGEXP_PASSWORD,
	REGEXP_PHONE_NUMBER,
	MAXIMUM_EMAIL_LENGTH,
	MAXIMUM_PHONE_NUMBER_LENGTH,
	MINIMUM_PASSWORD_LENGTH,
	MAXIMUM_PASSWORD_LENGTH,
};
