version: "3"

services:
    platform:
        ports:
            - 0:3000
        logging:
            driver: "awslogs"
            options:
                awslogs-region: eu-central-1
                awslogs-group: platform-legacy-${AWS_ENV}
                awslogs-stream-prefix: paratica
