version: "3"

services:
  platform:
    image: ${CI_REGISTRY_IMAGE:-paratica}/service-platform:legacy
    environment:
      SERVICE_NAME: platform-legacy
      NODE_ENV: ${AWS_ENV}
      REDIS_HOST: $MASTER_IP
      REDIS_PORT: 6380
      WAIT_HOSTS: ${DB_IP}:5433
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOSTS_TIMEOUT: 120
      KEYCLOAK_BASE_URL: https://aws-staging.paratica.com/auth
      KEYCLOAK_REALM: paratica
      KEYCLOAK_ADMIN_CLIENT_ID: paratica-backend
      KEYCLOAK_CLIENT_ID: paratica-rest
      DB_HOST: ${DB_IP}
      DB_PORT: 5433
      SERVICE_TAGS: "\
        backend,api,platform,\
        traefik.enable=true,\
        traefik.http.middlewares.platform-legacy-strip.stripPrefix.prefixes=/api/legacy/platform,\
        traefik.http.routers.platform-legacy.entrypoints=websecure,\
        traefik.http.routers.platform-legacy.rule=PathPrefix(`/api/legacy/platform`),\
        traefik.http.routers.platform-legacy.middlewares=platform-legacy-strip\\,jwt-auth,\
        traefik.http.routers.platform-legacy.tls=true"
