export { default as accountSettings, ReactComponent as AccountSettings } from "./account-settings.svg";
export { default as account, ReactComponent as Account } from "./account.svg";
export { default as activeUser, ReactComponent as ActiveUser } from "./active_user.svg";
export {
	default as algorithmicTradeMadeSimple,
	ReactComponent as AlgorithmicTradeMadeSimple,
} from "./algo_made_simple_for_all.svg";
export { default as appStore, ReactComponent as AppStore } from "./app-store.svg";
export { default as ArrowDown } from "./ArrowDown";
export { default as arrowDown } from "./arrow_down.svg";
export { default as arrowDownWhite, ReactComponent as ArrowDownWhite } from "./arrow_down_white.svg";
export { default as arrowLeft, ReactComponent as ArrowLeft } from "./arrow_left.svg";
export { default as arrowMiniLeft, ReactComponent as ArrowMiniLeft } from "./arrow_mini_left.svg";
export { default as arrowMiniRight, ReactComponent as ArrowMiniRight } from "./arrow_mini_right.svg";
export { default as arrowRight, ReactComponent as ArrowRight } from "./arrow_right.svg";
export { default as averageProfit, ReactComponent as AverageProfit } from "./average-profit.svg";
export { default as BacktestIcon } from "./BacktestIcon";
export { default as BacktestBackground } from "./backtest_background.jpg";
export { default as backtestIcon } from "./backtest_icon.svg";
export { default as bigCheck, ReactComponent as BigCheck } from "./big_check.svg";
export { default as binanceTrChip, ReactComponent as BinanceTrChip } from "./binanceTr_chip.svg";
export { default as binance1, ReactComponent as Binance1 } from "./binance_1.svg";
export { default as binanceChip, ReactComponent as BinanceChip } from "./binance_chip.svg";
export { default as bitmaxChip, ReactComponent as BitmaxChip } from "./bitmex_chip.svg";
export { default as blueSmallLogo, ReactComponent as BlueSmallLogo } from "./blue-small-logo.svg";
export { default as blueBg2 } from "./blue_bg_2.png";
export { default as bolt, ReactComponent as Bolt } from "./bolt.svg";
export { default as breadCrum, ReactComponent as BreadCrum } from "./bread-crum.svg";
export { default as build, ReactComponent as Build } from "./build.svg";
export { default as bullet, ReactComponent as Bullet } from "./bullet.svg";
export { default as cartCheck, ReactComponent as CartCheck } from "./cart_check.svg";
export { default as cartCheckSmall, ReactComponent as CartCheckSmall } from "./cart_check_small.svg";
export { default as Check } from "./Check";
export { default as checkOrange, ReactComponent as CheckOrange } from "./check-orange.svg";
export { default as check } from "./check.svg";
export { default as chevron, ReactComponent as Chevron } from "./chevron.svg";
export { default as close, ReactComponent as Close } from "./close.svg";
export { default as coinAnimation, ReactComponent as CoinAnimation } from "./coin_anima.svg";
export { default as collapse, ReactComponent as Collapse } from "./collapse.svg";
export { default as continue, ReactComponent as Continue } from "./continue.svg";
export { default as copyClipboard, ReactComponent as CopyClipboard } from "./copy_clipboard.svg";
export { default as Dashboard } from "./Dashboard";
export { default as deposit, ReactComponent as Deposit } from "./deposit.svg";
export { default as disabled, ReactComponent as Disabled } from "./disabled.svg";
export { default as discord, ReactComponent as DiscordIcon } from "./discord.svg";
export { default as done, ReactComponent as Done } from "./done.svg";
export { default as doubleEllipse, ReactComponent as DoubleEllipse } from "./double_ellipse.svg";
export { default as downMiniBlue, ReactComponent as DownMiniBlue } from "./down_mini_blue.svg";
export { default as dropDown, ReactComponent as DropDown } from "./drop_down.svg";
export { default as dropDownGray, ReactComponent as DropDownGray } from "./drop_down_gray.svg";
export { default as duplicate, ReactComponent as Duplicate } from "./duplicate.svg";
export { default as dyDxChip, ReactComponent as DyDxChip } from "./dydx_chip.svg";
export { default as edit, ReactComponent as Edit } from "./edit.svg";
export { default as ellipse, ReactComponent as Ellipse } from "./ellipse.svg";
export { default as emailVerification, ReactComponent as EmailVerification } from "./email_verification.svg";
export { default as exchangeCount, ReactComponent as ExchangeCount } from "./exchange_count.svg";
export { default as executionTypeLong, ReactComponent as ExecutionTypeLong } from "./execution_type_long.svg";
export { default as executionTypeShort, ReactComponent as ExecutionTypeShort } from "./execution_type_short.svg";
export { default as expand, ReactComponent as Expand } from "./expand.svg";
export { default as explorerMode1, ReactComponent as ExplorerMode1 } from "./explorer_mode_1.svg";
export { default as explorerMode2, ReactComponent as ExplorerMode2 } from "./explorer_mode_2.svg";
export { default as eyeOff, ReactComponent as EyeOff } from "./eye_off.svg";
export { default as eyeOn, ReactComponent as EyeOn } from "./eye_on.svg";
export { default as filter, ReactComponent as Filter } from "./filter.svg";
export { default as filterSettings, ReactComponent as FilterSetting } from "./filter_settings.svg";
export { default as filterSettingsGray, ReactComponent as FilterSettingGray } from "./filter_settings_gray.svg";
export { default as fireIcon, ReactComponent as FireIcon } from "./fire_icon.svg";
export { default as Follower } from "./Follower";
export { default as follower } from "./follower.svg";
export { default as followNoStrategy, ReactComponent as FollowNoStrategy } from "./follow_no_strategy.svg";
export { default as ffxTRChip, ReactComponent as FfxTRChip } from "./ftxTr_chip.svg";
export { default as ftxChip, ReactComponent as FtxChip } from "./FTX_chip.svg";
export { default as futures, ReactComponent as Futures } from "./futures.svg";
export { default as futureChip, ReactComponent as FutureChip } from "./future_chip.svg";
export { default as googlePlay, ReactComponent as GooglePlay } from "./google-play.svg";
export { default as graphPlaceholder, ReactComponent as GraphPlaceholder } from "./graph_placehoder.svg";
export { default as group, ReactComponent as Group } from "./group.svg";
export { default as header, ReactComponent as Header } from "./header.svg";
export { default as help, ReactComponent as Help } from "./help.svg";
export { default as Home } from "./Home";
export { default as huobiChip, ReactComponent as HuobiChip } from "./huobi_chip.svg";
export { default as identityVerification, ReactComponent as IdentityVerification } from "./identity_verification.svg";
export { default as infoOrange, ReactComponent as InfoOrange } from "./info-orange.svg";
export { default as info, ReactComponent as Info } from "./info.svg";
export { default as info_blue, ReactComponent as InfoBlue } from "./info_blue.svg";
export { default as islemsirasi, ReactComponent as IslemSirasi } from "./islem-sirasi.svg";
export { default as LeaderBoard } from "./LeaderBoard";
export { default as LeaderboardArrow } from "./LeaderboardArrow";
export { default as leaderBoardIcon, ReactComponent as LeaderboardIcon } from "./leaderboard_icon.svg";
export { default as lightning, ReactComponent as Lightning } from "./lightning.svg";
export { default as line, ReactComponent as Line } from "./line.svg";
export { default as linkedinBlue, ReactComponent as LinkedinBlue } from "./linkedin_blue.svg";
export { default as loading, ReactComponent as Loading } from "./loading.svg";
export { default as loginPage1, ReactComponent as LoginPage1 } from "./login_page_1.svg";
export { default as loginPage2, ReactComponent as LoginPage2 } from "./login_page_2.svg";
export { default as loginPage3, ReactComponent as LoginPage3 } from "./login_page_3.svg";
export { default as loginPage4, ReactComponent as LoginPage4 } from "./login_page_4.svg";
export { default as loginPage5, ReactComponent as LoginPage5 } from "./login_page_5.svg";
export { default as logo, ReactComponent as Logo } from "./logo.svg";
export { default as longChip, ReactComponent as LongChip } from "./long_chip.svg";
export { default as manage, ReactComponent as Manage } from "./manage.svg";
export { default as market, ReactComponent as Market } from "./market.svg";
export { default as MarketPlace } from "./MarketPlace";
export { default as maximumDrawdown, ReactComponent as MaximumDrawdown } from "./maximum_drawdown.svg";
export { default as MenuDashboard } from "./MenuDashboard";
export { default as MenuExchange } from "./MenuExchange";
export { default as MenuExpert } from "./MenuExpert";
export { default as MenuLeaderboard } from "./MenuLeaderboard";
export { default as MenuMarketPlace } from "./MenuMarketplace";
export { default as MenuPositionsCenter } from "./MenuPositionsCenter";
export { default as MenuRobots } from "./MenuRobots";
export { default as MenuWallet } from "./MenuWallet";
export { default as MenuWorkshop } from "./MenuWorkshop";
export { default as noBannerCover } from "./noBannerCover.svg";
export { default as notification, ReactComponent as Notification } from "./notification.svg";
export { default as notifications, ReactComponent as Notifications } from "./notifications.svg";
export { default as okexChip, ReactComponent as OkexChip } from "./okex_chip.svg";
export { default as operationsCheck, ReactComponent as OperationsCheck } from "./operations-check.svg";
export { default as operationsDelete, ReactComponent as OperationsDelete } from "./operations-delete.svg";
export { default as operationsDisable, ReactComponent as OperationsDisable } from "./operations-disable.svg";
export { default as operationsUpdate, ReactComponent as OperationsUpdate } from "./operations-update.svg";
export { default as package, ReactComponent as Package } from "./package.svg";
export { default as plus, ReactComponent as Plus } from "./plus.svg";
export { default as pnlUp, ReactComponent as PNLup } from "./pnl_up.svg";
export { default as popular, ReactComponent as Popular } from "./popular.svg";
export { default as positionsCount, ReactComponent as PositionsCount } from "./positions_count.svg";
export { default as previousPage, ReactComponent as PreviousPage } from "./previous_page.svg";
export { default as profileBadge, ReactComponent as ProfileBadge } from "./profile_badge.svg";
export { default as profilePerson, ReactComponent as ProfilePerson } from "./profile_person.svg";
export { default as ProperCheck } from "./ProperCheck";
export { default as proveId, ReactComponent as ProveId } from "./proveid_logo.svg";
export { default as Questbox } from "./Questbox";
export { default as radioChecked, ReactComponent as RadioChecked } from "./radio_checked.svg";
export { default as radioUnchecked, ReactComponent as RadioUnchecked } from "./radio_unchecked.svg";
export { default as referansParaticas, ReactComponent as ReferansParaticas } from "./referans_paraticas.svg";
export { default as reference, ReactComponent as Reference } from "./reference.svg";
export { default as registerSuccess, ReactComponent as RegisterSuccess } from "./register_success.svg";
export { default as returnBack, ReactComponent as ReturnBack } from "./return-back.svg";
export { default as rewardCredit, ReactComponent as RewardCredit } from "./reward_credit.svg";
export { default as risk, ReactComponent as Risk } from "./risk.svg";
export { default as run, ReactComponent as Run } from "./run.svg";
export { default as save, ReactComponent as Save } from "./save.svg";
export { default as scroll, ReactComponent as Scroll } from "./scroll.svg";
export { default as scrollUp, ReactComponent as ScrollUp } from "./scroll_up.svg";
export { default as search, ReactComponent as Search } from "./search.svg";
export { default as searchIcon, ReactComponent as SearchIcon } from "./search_icon.svg";
export { default as secureAddress, ReactComponent as SecureAddress } from "./secure_address.svg";
export { default as security, ReactComponent as Security } from "./security.svg";
export { default as notificationSettings, ReactComponent as NotificationSettings } from "./settings-notification.svg";
export { default as settings, ReactComponent as Settings } from "./settings.svg";
export { default as sharpeRatio, ReactComponent as SharpeRatio } from "./sharpe_ratio.svg";
export { default as shortChip, ReactComponent as ShortChip } from "./short_chip.svg";
export { default as shortIcon, ReactComponent as ShortIcon } from "./short_icon.svg";
export { default as sideFutures, ReactComponent as SideFutures } from "./side_futures.svg";
export { default as sideLong, ReactComponent as SideLong } from "./side_long.svg";
export { default as sideShort, ReactComponent as SideShort } from "./side_short.svg";
export { default as sideSpot, ReactComponent as SideSpot } from "./side_spot.svg";
export { default as signal, ReactComponent as Signal } from "./signal.svg";
export { default as signalVirtual, ReactComponent as SignalVirtual } from "./signal_virtual.svg";
export { default as slideIcon } from "./slidew.svg";
export { default as smallLogo, ReactComponent as SmallLogo } from "./small_logo.svg";
export { default as smsVerification, ReactComponent as SmsVerification } from "./sms_verification.svg";
export { default as spotUp2, ReactComponent as SpotUp2 } from "./spot-up2.svg";
export { default as SpotDown } from "./SpotDown";
export { default as SpotUp } from "./SpotUp";
export { default as spotChip, ReactComponent as SpotChip } from "./spot_chip.svg";
export { default as spotDown2, ReactComponent as SpotDown2 } from "./spot_down_2.svg";
export { default as spotRight, ReactComponent as SpotRight } from "./spot_right.svg";
export { default as stagedLogo, ReactComponent as StagedLogo } from "./staged_logo.svg";
export { default as standby, ReactComponent as Standby } from "./standby.svg";
export { default as starEmpty, ReactComponent as StarEmpty } from "./star_empty.svg";
export { default as starFilled, ReactComponent as StarFilled } from "./star_filled.svg";
export { default as step1, ReactComponent as Step1 } from "./step1.svg";
export { default as step2, ReactComponent as Step2 } from "./step2.svg";
export { default as stepperEye, ReactComponent as StepperEye } from "./stepper_eye.svg";
export { default as stockBtnTicker, ReactComponent as StockBtnTicker } from "./stock_btn_ticker.svg";
export { default as stop, ReactComponent as Stop } from "./stop.svg";
export { default as success, ReactComponent as Success } from "./success.svg";
export { default as success2, ReactComponent as Success2 } from "./success_2.svg";
export { default as successRate, ReactComponent as SuccessRate } from "./success_rate.svg";
export { default as switch, ReactComponent as Switch } from "./switch.svg";
export { default as sync, ReactComponent as Sync } from "./sync.svg";
export { default as telegram, ReactComponent as Telegram } from "./telegram.svg";
export { default as telegramTraderLogo, ReactComponent as TelegramTraderLogo } from "./telegram_trader_logo.svg";
export { default as time, ReactComponent as Time } from "./time.svg";
export { default as tooltipCheck, ReactComponent as TooltipCheck } from "./tooltip_check.svg";
export { default as tooltipStop, ReactComponent as TooltipStop } from "./tooltip_stop.svg";
export { default as totalProfitPercent, ReactComponent as TotalProfitPercent } from "./total_profit_percent.svg";
export { default as trace, ReactComponent as Trace } from "./trace.svg";
export { default as tradingview, ReactComponent as TradingViewIcon } from "./tradingview.svg";
export { default as tradingviewBlue, ReactComponent as TradingViewIconBlue } from "./tradingview_blue.svg";
export { default as trash, ReactComponent as Trash } from "./trash.svg";
export { default as trendStrategies, ReactComponent as TrendStrategies } from "./trend_strategies.svg";
export { default as twitter, ReactComponent as TwitterIcon } from "./twitter.svg";
export { default as twitterBlue, ReactComponent as TwitterIconBlue } from "./twitter_blue.svg";
export { default as unfollow, ReactComponent as Unfollow } from "./unfollow.svg";
export { default as Uri } from "./Uri";
export { default as uri } from "./uri.svg";
export { default as UriPrime } from "./UriPrime";
export { default as uriCharacter, ReactComponent as UriCharacter } from "./uri_character.svg";
export { default as uriGray2, ReactComponent as UriGray2 } from "./uri_gray_2.svg";
export { default as uriPrime } from "./uri_prime.svg";
export { default as uriPrimeGray } from "./uri_prime_gray.svg";
export { default as uriRejected, ReactComponent as UriRejected } from "./uri_rejected.svg";
export { default as uriText, ReactComponent as UriText } from "./uri_text.svg";
export { default as uriWait, ReactComponent as UriWait } from "./uri_wait.svg";
export { default as usdtTether, ReactComponent as UsdtTether } from "./usdt_tether.svg";
export { default as vectorStrokeLink, ReactComponent as VectorStrokeLink } from "./vector _stroke_link.svg";
export {
	default as vectorStrokeLinkBlue,
	ReactComponent as VectorStrokeLinkBlue,
} from "./vector _stroke_link_blue.svg";
export { default as verificationCode, ReactComponent as VerificationCode } from "./verification_code.svg";
export { default as viewChart, ReactComponent as ViewChart } from "./view-chart.svg";
export { default as virtual, ReactComponent as Virtual } from "./virtual.svg";
export { default as waiting, ReactComponent as Waiting } from "./waiting.svg";
export { default as wallclock, ReactComponent as WallClock } from "./wall-clock.svg";
export { default as wallet, ReactComponent as Wallet } from "./wallet.svg";
export { default as wallet2, ReactComponent as Wallet2 } from "./wallet2.svg";
export { default as withdraw, ReactComponent as Withdraw } from "./withdraw.svg";
export { default as youtube, ReactComponent as YoutubeIcon } from "./youtube.svg";
export { default as youtubeIconBlue, ReactComponent as YoutubeIconBlue } from "./youtube_blue.svg";
