const koaRateLimit = require("koa-ratelimit");

const { redis } = require("../services/redis");

const COMMON_GET_SETTINGS = {
	duration: 10,
	count: 50,
};

const COMMON_POST_SETTINGS = {
	duration: 10,
	count: 5,
};

const COMMON_PUT_SETTINGS = {
	duration: 10,
	count: 5,
};

const RATE_LIMIT_ROUTE_MAP = {
	"/register": COMMON_POST_SETTINGS,
	"/login": {
		duration: 20,
		count: 10,
	},
	"/login/method/request": {
		duration: 20,
		count: 10,
	},
	"/login/confirm": {
		duration: 20,
		count: 10,
	},
	"/forgot-password": COMMON_POST_SETTINGS,
	"/merchant/create": {
		duration: 10,
		count: 1,
	},
	"/merchant/update": COMMON_POST_SETTINGS,
	"/agreement/post": COMMON_POST_SETTINGS,
	"/billing-address/get": COMMON_GET_SETTINGS,
	"/billing-address/post": COMMON_POST_SETTINGS,
	"/version-info/get": COMMON_GET_SETTINGS,
	"/version-info/post": COMMON_POST_SETTINGS,
	"/notification": COMMON_POST_SETTINGS, //--
	"/notifications/get": COMMON_GET_SETTINGS,
	"/notifications/count": COMMON_GET_SETTINGS,
	"/notification/id/get": COMMON_GET_SETTINGS,
	"/notification/put": COMMON_PUT_SETTINGS,
	"/notification/id/put": COMMON_PUT_SETTINGS,
	"/notifications/types": COMMON_GET_SETTINGS,
	"/notification-setting/get": COMMON_GET_SETTINGS,
	"/notification-setting/patch": COMMON_PUT_SETTINGS,
	"/otp/request": COMMON_POST_SETTINGS,
	"/otp/send": COMMON_POST_SETTINGS,
	"/otp/confirm": COMMON_POST_SETTINGS,
	"/confirm-otp": COMMON_POST_SETTINGS,
	"/otp/send-deposit": COMMON_POST_SETTINGS,
	"/otp/confirm-deposit": COMMON_POST_SETTINGS,
	"/send-otp-again": COMMON_POST_SETTINGS,
	"/profile/get": COMMON_GET_SETTINGS,
	"/profile/post": COMMON_POST_SETTINGS,
	"/profile/file/upload": COMMON_POST_SETTINGS,
	"/annul/start": COMMON_POST_SETTINGS,
	"/annul/method/request": COMMON_POST_SETTINGS,
	"/annul/confirm": COMMON_PUT_SETTINGS,
	"/reference-codes": COMMON_GET_SETTINGS,
	"/reference-code/id": COMMON_GET_SETTINGS,
	"/reference-code/post": COMMON_POST_SETTINGS,
	"/reference-code/patch": COMMON_PUT_SETTINGS,
	"/reference-code/put": COMMON_PUT_SETTINGS,
	"/security-settings/patch": COMMON_PUT_SETTINGS,
	"/security-settings/get": COMMON_GET_SETTINGS,
	"/ip-whitelist": COMMON_POST_SETTINGS,
	"/twofa-settings": COMMON_POST_SETTINGS,
	"/telegram-code": COMMON_GET_SETTINGS,
	"/transaction/start": COMMON_POST_SETTINGS,
	"/twofa": COMMON_POST_SETTINGS,
	"/contact-info": COMMON_PUT_SETTINGS,
	"/device-info/patch": COMMON_PUT_SETTINGS,
	"/device-info/get": COMMON_GET_SETTINGS,
	"/password/update": COMMON_POST_SETTINGS,
	"/wafer": COMMON_POST_SETTINGS,
	"/health-check": COMMON_GET_SETTINGS,
	"/positions": COMMON_GET_SETTINGS,
	"/positions/count": COMMON_GET_SETTINGS,
	"/positions/filter": COMMON_GET_SETTINGS,
	"/positions/export": COMMON_POST_SETTINGS,
	"/positions/manualExit": COMMON_POST_SETTINGS,
	"/strategy-successes": COMMON_GET_SETTINGS,
	"/strategy-success/id": COMMON_GET_SETTINGS,
	"/strategies/followed": COMMON_GET_SETTINGS,
	"/strategies/unfollowed": COMMON_GET_SETTINGS,
	"/strategy-follower/strategyId": COMMON_GET_SETTINGS,
	"/strategy-followers/strategyId": COMMON_PUT_SETTINGS,
	"/strategy-follower": COMMON_POST_SETTINGS,
	"/strategy/strategyId/followed/status": COMMON_PUT_SETTINGS,
	"/strategy/strategyId/followed/budget": COMMON_POST_SETTINGS,
	"/strategy/strategyId/followed/blacklist": COMMON_POST_SETTINGS,
	"/strategy/strategyId/followed/position-settings": COMMON_PUT_SETTINGS,
	"/strategies": COMMON_GET_SETTINGS,
	"/strategy/id/get": COMMON_GET_SETTINGS,
	"/strategy/id/put": COMMON_PUT_SETTINGS,
	"/strategy/id/delete": COMMON_PUT_SETTINGS,
	"/strategy/id/duplicate": COMMON_POST_SETTINGS,
	"/strategy": COMMON_POST_SETTINGS,
	"/rule-designs": COMMON_GET_SETTINGS,
	"/rule-design/id": COMMON_GET_SETTINGS,
	"/rule-design": COMMON_POST_SETTINGS,
	"/indicators": COMMON_GET_SETTINGS,
	"/funnels": COMMON_GET_SETTINGS,
	"/funnel/id/get": COMMON_GET_SETTINGS,
	"/funnel/id/put": COMMON_PUT_SETTINGS,
	"/funnel": COMMON_POST_SETTINGS,
	"/market-strategies": COMMON_GET_SETTINGS,
	"/market-strategies/count": COMMON_GET_SETTINGS,
	"/market-strategy/id": COMMON_GET_SETTINGS,
	"/market-strategy/id/follow": COMMON_POST_SETTINGS,
	"/market-strategy": COMMON_POST_SETTINGS,
	"/market-strategy/id/status": COMMON_POST_SETTINGS,
	"/market-strategy-metric": COMMON_GET_SETTINGS,
	"/general-market-metrics": COMMON_GET_SETTINGS,
	"/merchant/id": COMMON_GET_SETTINGS,
	"/merchants": COMMON_GET_SETTINGS,
	"/merchant/id/status": COMMON_POST_SETTINGS,
	"/coinspaid/user-wallet-address": COMMON_POST_SETTINGS,
	"/coinspaid/withdrawal/start": COMMON_POST_SETTINGS,
	"/coinspaid/method/request": COMMON_POST_SETTINGS,
	"/coinspaid/withdrawal/confirm": COMMON_POST_SETTINGS,
	"/coinspaid/callback": COMMON_GET_SETTINGS,
	"/kyc/start": COMMON_GET_SETTINGS,
	"/kyc/proxy": COMMON_POST_SETTINGS,
	"/connections": COMMON_GET_SETTINGS,
	"/connection/exchange": COMMON_GET_SETTINGS,
	"/connection": COMMON_POST_SETTINGS,
	"/connection/exchange/recheck": COMMON_POST_SETTINGS,
	"/connection-update": COMMON_POST_SETTINGS,
	"/connection/exchange/delete": COMMON_POST_SETTINGS,
	"/connection/exchange/active": COMMON_POST_SETTINGS,
	"/parities": COMMON_GET_SETTINGS,
	"/parities/details": COMMON_POST_SETTINGS,
	"/platforms": COMMON_GET_SETTINGS,
	"/backtest/id": COMMON_GET_SETTINGS,
	"/backtest/id/positions": COMMON_GET_SETTINGS,
	"/backtest/id/delete": COMMON_PUT_SETTINGS,
	"/backtests": COMMON_GET_SETTINGS,
	"/backtest": COMMON_POST_SETTINGS,
	"/backtest-position": COMMON_POST_SETTINGS,
	"/campaign": COMMON_POST_SETTINGS,
	"/campaigns": COMMON_GET_SETTINGS,
	"/campaign/id/get": COMMON_GET_SETTINGS,
	"/campaign/id/put": COMMON_PUT_SETTINGS,
	"/campaign/id/eligibility": COMMON_GET_SETTINGS,
	"/campaign/id/attendance/post": COMMON_POST_SETTINGS,
	"/campaign/id/attendance/get": COMMON_GET_SETTINGS,
	"/campaign/id/status": COMMON_PUT_SETTINGS,
	"/campaign/id/claim": COMMON_PUT_SETTINGS,
	"/config": COMMON_GET_SETTINGS,
	"/favorite-coins/get": COMMON_GET_SETTINGS,
	"/favorite-coins/post": COMMON_POST_SETTINGS,
	"/historical-balance-summary": COMMON_GET_SETTINGS,
	"/portfolio": COMMON_GET_SETTINGS,
	"/position-summary": COMMON_GET_SETTINGS,
	"/stories": COMMON_GET_SETTINGS,
	"/story/id/get": COMMON_GET_SETTINGS,
	"/story/id/put": COMMON_PUT_SETTINGS,
	"/story": COMMON_POST_SETTINGS,
	"/topics": COMMON_GET_SETTINGS,
	"/topic/id/get": COMMON_GET_SETTINGS,
	"/topic/id/put": COMMON_PUT_SETTINGS,
	"/topic": COMMON_POST_SETTINGS,
	"/wallet": COMMON_GET_SETTINGS,
	"/wallet/transactions-summary": COMMON_GET_SETTINGS,
	"/wallet/transaction-details": COMMON_GET_SETTINGS,
	"/leaderboard": COMMON_GET_SETTINGS,
	"/leaderboard/self": COMMON_GET_SETTINGS,
	"/leaderboard/proximity": COMMON_GET_SETTINGS,
};

const _rateLimit = ({ duration = 30, count = 5, route = "unknown" }) =>
	koaRateLimit({
		driver: "redis",
		db: redis,
		duration: duration * 1000, // in milliseconds
		errorMessage: {
			message: "",
			error: {
				code: "001",
				detail: `Too many requests, wait for ${duration} seconds.`,
			},
		},
		id: (ctx) => `${route}:${ctx.request.header["cf-connecting-ip"] ?? ctx.request.ip}`,
		headers: {
			remaining: "Rate-Limit-Remaining",
			reset: "Rate-Limit-Reset",
			total: "Rate-Limit-Total",
		},
		max: count,
		disableHeader: false,
	});

const rateLimit = (route) => _rateLimit({ ...RATE_LIMIT_ROUTE_MAP[route], route });

module.exports = rateLimit;
