// https://docs.google.com/document/d/1Qd88X8GWPu046RSB2Gffl6VLDipybVdJ/

export default {
	"104": "error.phoneNumber or email is already using by another user",
	"105": "error.user not found",
	"106": "error.user not verified",
	"107": "error.token expired",
	"108": "error.reference code not found",
	"109": "error.invalid notification reason",
	"110": "Error received during update",
	"111": "error received during register",
	"201": "Wrong exchange",
	"202": "Connections not exist",
	"203": "Error from cex",
	"204": "No old connections",
	"401": "Market strategy not found",
	"402": "Strategy not found",
	"403": "Merchant not found",
	"404": "price must be in range",
	"405": "api_error_max_parity_count_reached",
	"501": "followed strategy not exist",
	"601": "email security not active",
	"602": "sms security not active",
	"603": "otp code false",
	"604": "twofa not set",
	"605": "Phone number not verified",
	"606": "Email not verified",
	"607": "default coins not set",
	"608": "contactInfoKey not found",
	"701": "conversationId not found",
	"702": "invalid token",
	"703": "Invalid signature or key",
	"704": "insufficient balance",
	"705": "uncompleted withdrawal request exists",
	"706": "no pending withdrawal request exists",
	"801": "Backtest not found.",
	"901": "uncompleted exchange request exists",
	"002": "invalid credentials",
	"006": "transaction required for endpoint",
	"004": "emailCode required for endpoint",
	"005": "smsCode required for endpoint",
	"003": "twofaCode required for endpoint",
	"007": "operation not match",
	"008": "passwords now match",
};
