version: "3"

services:
    campaign-leaderboard-calculator-cronjob:
        ports:
            - 0:3000
        logging:
            driver: "awslogs"
            options:
                awslogs-region: eu-central-1
                awslogs-group: campaign-leaderboard-calculator-cronjob-${AWS_ENV}
                awslogs-stream-prefix: paratica
