version: "3"

services:
    api-end-time-reminder-cronjob:
        ports:
            - 0:3000
        logging:
            driver: "awslogs"
            options:
                awslogs-region: eu-central-1
                awslogs-group: api-end-time-reminder-cronjob-${AWS_ENV}
                awslogs-stream-prefix: paratica
